# Composed of fs026/27/17 mutated to host OVB jobs
# scenario062-multinode-containers.yaml
# is invoked with scenario_args instead of composable_scenario!
composable_scenario: ""
scenario_args: "-e tht/config/general_config/featureset062.yml"
deployed_server: false
# Enable, if deployed from vanila Centos images
undercloud_setup: false
step_install_undercloud: true
undercloud_enable_validations: false
undercloud_undercloud_debug: false
undercloud_enable_ui: false
undercloud_enable_tempest: false

enable_swap: true
swap_type: file
network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true
containerized_undercloud: true
undercloud_install_cli_options: " --use-heat"
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"
undercloud_resource_registry_args:
  "OS::TripleO::Undercloud::Net::SoftwareConfig": "{{ overcloud_templates_path }}/ci/common/net-config-simple-bridge.yaml"
undercloud_extra_services_args: "-e {{overcloud_templates_path}}/environments/docker.yaml"
undercloud_extra_args: ""
deploy_steps_ansible_workflow: true
undercloud_rpm_dependencies: "python-tripleoclient*"

# turn on image prep
step_overcloud_image: true
step_glance_upload: true
step_register: true
step_root_device_size: true
step_root_device_hints: true
step_introspect: true

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

extra_args: >-
  --ntp-server pool.ntp.org

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
test_ping: false
run_tempest: false
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
  - name: Compute
    CountDefault: 1
    tags:
      - compute
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
