# Undercloud TLS all-in-one BM(maybe) and VM-libvirt scenario to host openshift VMs.
# Must be applied top-scope via -e@.
# Based on fs027 from quickstart.
# Assumes eth0 is libvirt brext or phys ext-net. And eth1 is internal ctlplane (phys/brovc).
undercloud_vcpu: 6
undercloud_memory: 20480
enable_opstools_repo: false
deployed_server: false
deploy_multinode: false
extra_tht_configs: /tmp/scripts/tht
configure_repos: true
enable_vbmc: false
undercloud_enable_ui: false
enable_libvirt_tripleo_ui: false
release: master
dlrn_hash_tag: current-tripleo
undercloud_undercloud_debug: false
undercloud_cloud_domain: localdomain
undercloud_enable_ironic: false
undercloud_enable_ironic_inspector: false
undercloud_enable_telemetry: false
undercloud_enable_zaqar: true
undercloud_enable_mistral: true
undercloud_install_cli_options: " --use-heat"
# FIXME hack in self-hosted Mistral for octavia:
# that env file should only be added on a 2nd deploy run!
# {{overcloud_templates_path}}/environments/services-docker/octavia.yaml
undercloud_custom_env_files: >-
 {{overcloud_templates_path}}/environments/services-docker/undercloud-cinder.yaml,
 {{overcloud_templates_path}}/environments/disable-telemetry.yaml,
 {{working_dir}}/undercloud-parameter-defaults.yaml
# FIXME undercloud-deploy.sh can not be used with a custom undercloud_ip,
# different to the one generated with libivrt setup inventory tasks
undercloud_install_script: undercloud-install.sh.j2
undercloud_docker_registry_host: docker.io
undercloud_docker_registry_namespace: tripleomaster
undercloud_docker_image_tag: "{{ dlrn_hash_tag }}"
network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: false
containerized_undercloud: true
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"
step_install_undercloud: true
step_overcloud_image: false
step_glance_upload: false
step_register: false
step_root_device_size: false
step_root_device_hints: false
step_introspect: false
undercloud_generate_service_certificate: true
ssl_overcloud: false
test_ping: false
run_tempest: false
enable_port_forward_for_tripleo_ui: false
delete_docker_cache: true
undercloud_rpm_dependencies: "python-tripleoclient*"
# The flat external co-located with internal/isolated ctlplane network CIDR
undercloud_network_cidr: 192.168.23.0/24
undercloud_local_interface: eth0
undercloud_network_gateway: "{{ undercloud_network_cidr|nthhost(1) }}"
undercloud_local_ip: "{{ hostvars['undercloud'].undercloud_ip }}/{{ undercloud_network_cidr|ipaddr('prefix') }}"
# Use remote/local KVM host registry IP otherwise
# e.g. undercloud_external_network_cidr|nthhost(1)
local_docker_registry_host: "{{ hostvars['undercloud'].undercloud_ip }}"
# The external (to UC) network CIDR and interface routed from the remote
# ansible control node or local libvirt host. We want it reachable from
# outside (or local KVM host), for ansible to access Heat et al APIs and
# provision VMs for openshift clusters.
# Undercloud_ip comes from it at the libvirt-provision stage.
undercloud_external_network_cidr: 192.168.23.0/24
undercloud_external_network_gateway: "{{ undercloud_external_network_cidr|nthhost(1) }}"
# Assumes the external/admin network dhcp range ends on .50
undercloud_undercloud_public_host: "{{ undercloud_external_network_cidr|nthhost(51) }}"
undercloud_undercloud_admin_host: "{{ undercloud_network_cidr|nthhost(52) }}"
# FIXME Or should these be undercloud_network_cidr?..
# It would be nice to provision non-nested VMs, which reside on the external
# libvirt/BM network instead of the isolated ctlplane!
undercloud_masquerade_network: "{{ undercloud_external_network_cidr }}"
undercloud_dhcp_start: "{{ undercloud_external_network_cidr|nthhost(60) }}"
undercloud_dhcp_end: "{{ undercloud_external_network_cidr|nthhost(69) }}"
# Not really used here as all-in-one does not include Ironic (for now)
undercloud_inspection_iprange: "{{ undercloud_external_network_cidr|nthhost(70) }},{{ undercloud_external_network_cidr|nthhost(79) }}"
undercloud_undercloud_nameservers:
  - 208.67.222.220
undercloud_resource_registry_args:
  "OS::TripleO::Undercloud::Net::SoftwareConfig": "{{ overcloud_templates_path }}/net-config-undercloud.yaml"
  "OS::TripleO::Network::Ports::RedisVipPort": "{{ overcloud_templates_path }}/network/ports/noop.yaml"
  "OS::TripleO::Network::Ports::ControlPlaneVipPort": "{{ overcloud_templates_path }}/deployed-server/deployed-neutron-port.yaml"
  "OS::TripleO::NodeExtraConfigPost": "{{ overcloud_templates_path }}/extraconfig/post_deploy/undercloud_post.yaml"
  "OS::TripleO::Services::DockerRegistry": "{{ overcloud_templates_path }}/puppet/services/docker-registry.yaml"
  "OS::TripleO::Network::Ports::ExternalVipPort": "{{ overcloud_templates_path }}/network/ports/external_from_pool.yaml"
undercloud_network_environment_args:
  ExternalNetCidr: "{{ undercloud_external_network_cidr }}"
  ExternalAllocationPools: >
    [{'start': '{{ undercloud_external_network_cidr|nthhost(128) }}',
    'end': '{{ undercloud_external_network_cidr|nthhost(250) }}'}]
  ControlPlaneSubnetCidr: "{{ undercloud_network_cidr|ipaddr('prefix') }}"
  ControlPlaneDefaultRoute: "{{ undercloud_network_gateway }}"
  EC2MetadataIp: "{{ hostvars['undercloud'].undercloud_ip }}"
  DnsServers: "{{ undercloud_undercloud_nameservers }}"
  ControlPlaneStaticRoutes:
    - ip_netmask: 169.254.169.254/32
      next_hop: "{{ undercloud_network_gateway }}"
    - ip_netmask: "{{ undercloud_network_cidr }}"
      next_hop: "{{ undercloud_network_gateway }}"
    - ip_netmask: "{{ undercloud_external_network_cidr }}"
      next_hop: "{{ undercloud_external_network_gateway }}"
    - ip_netmask: 0.0.0.0/0
      next_hop: "{{ undercloud_external_network_gateway }}"
  UndercloudCtlplaneSubnets:
    ctlplane-subnet:
      NetworkCidr: "{{ undercloud_network_cidr }}"
      NetworkGateway: "{{ undercloud_network_gateway }}"
      DhcpRangeStart: "{{ undercloud_network_cidr|nthhost(5) }}"
      DhcpRangeEnd: "{{ undercloud_network_cidr|nthhost(24) }}"
  UndercloudCtlplaneLocalSubnet: 'ctlplane-subnet'
  # It should match the undercloud_local_interface value
  NeutronPublicInterface: eth0
  HypervisorNeutronPublicInterface: eth0
  KernelIpForward: 1
  KeystoneCorsAllowedOrigin: '*'
  TokenExpiration: 14400
  HeatConvergenceEngine: true
  Debug: false
  DockerDebug: false
  DockerPuppetDebug: false
  GlanceBackend: 'swift'
  NotificationDriver: 'noop'
  SwiftCeilometerPipelineEnabled: false
  EnablePackageInstall: true
  StackAction: CREATE
  SoftwareConfigTransport: POLL_SERVER_HEAT
  NeutronTunnelTypes: []
  NeutronFlatNetworks: '*'
  NeutronDnsDomain: 'openshift.cluster.lc'
  NovaSchedulerAvailableFilters: 'tripleo_common.filters.list.tripleo_filters'
  NovaSchedulerDefaultFilters: ['RetryFilter', 'TripleOCapabilitiesFilter', 'ComputeCapabilitiesFilter', 'AvailabilityZoneFilter', 'RamFilter', 'DiskFilter', 'ComputeFilter', 'ImagePropertiesFilter', 'ServerGroupAntiAffinityFilter', 'ServerGroupAffinityFilter']
  NovaSchedulerMaxAttempts: 30
  NovaAutoDisabling: '0'
  NeutronDhcpAgentsPerNetwork: 2
  HeatConvergenceEngine: false
  HeatCorsAllowedOrigin: '*'
  HeatMaxResourcesPerStack: -1
  HeatMaxJsonBodySize: 2097152
  MistralExecutionFieldSizeLimit: 16384
  MistralCorsAllowedOrigin: '*'
  MistralExecutionFieldSizeLimit: 16384
  NeutronExternalNetworkBridge: "''"
  NeutronBridgeMappings: 'floating:br-ex,ctlplane:br-ctlplane'
  NeutronServicePlugins: 'router,qos,trunk,segments'
  NeutronPluginExtensions: 'qos,port_security,dns,dns_domain_ports'
  NeutronAgentExtensions: 'qos'
  NeutronNetworkVLANRanges: 'physnet1:1000:2999'
  NeutronPluginExtensions: 'port_security'
  NeutronFirewallDriver: ''
  NeutronNetworkType: ['local','flat','vlan','gre','vxlan']
  NeutronTunnelIdRanges: '20:100'
  NeutronTypeDrivers: ['local','flat','vlan','gre','vxlan']
  NeutronVniRanges: '10:100'
  NeutronPortQuota: '-1'
  MigrateLegacyNeutronDb: true
  SwiftCorsAllowedOrigin: '*'
