---
# Non local deployments by quickstart
- name: Install delorian repos
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  become: true
  vars_files:
    - vars/undercloud-traas.yaml
  roles:
    - repo-setup

- name: Install the client
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  become: true
  tasks:
    - package:
        name: python-tripleoclient

- name: Install the undercloud (oooq-extras)
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: true
  become: false
  vars_files:
    - vars/undercloud-traas.yaml
  roles:
    - undercloud-deploy
