---
# Non local deployments by quickstart
- name: Install delorian repos
  hosts: overcloud
  any_errors_fatal: true
  gather_facts: false
  become: true
  vars_files:
    - vars/overcloud-traas.yaml
  roles:
    - repo-setup

- name: Run overcloud prep roles
  hosts: undercloud
  any_errors_fatal: true
  vars_files:
    - vars/overcloud-traas.yaml
  gather_facts: false
  become: true
  roles:
    - overcloud-prep-config
    - overcloud-prep-containers

- name:  Deploy the overcloud (multinode)
  any_errors_fatal: true
  hosts: undercloud
  gather_facts: true
  become: false
  vars_files:
    - vars/overcloud-traas.yaml
  roles:
    - overcloud-deploy
  #TODO parametrize env vars for the deployed-server remaining roles
  environment:
    OVERCLOUD_ROLES: "{{overcloud_deployed_roles}}"
    ControllerDeployedServer_hosts: "{{controller_hosts}}"
    SUBNODES_SSH_KEY: "{{subnodes_ssh_key}}"
  #  ComputeDeployedServer_hosts: "{{compute_hosts}}"

- name: Add the overcloud nodes to the generated inventory
  any_errors_fatal: true
  hosts: undercloud
  gather_facts: false
  vars_files:
    - vars/overcloud-traas.yaml
  become: false
  tags:
    - overcloud-deploy
  vars:
      inventory: all
  roles:
    - tripleo-inventory
