---
- name: Provision tasks
  hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  become: true
  roles:
    # FIXME(bogdando) fails to restart libvirt in the chrooted container
    # allow the "roles/parts/libvirt/tasks/main.yml" to fail!
    - { role: environment/setup, when: teardown|bool }
    - { role: libvirt/teardown, when: teardown|bool }
    - { role: libvirt/setup/user, when: teardown|bool, become: false }
    #- libvirt/setup/overcloud
    - libvirt/setup/undercloud

- name: Generate new inventory
  hosts: localhost
  any_errors_fatal: true
  gather_facts: no
  become: false
  roles:
    - { role: tripleo-inventory, tags: undercloud-inventory }
