---
- name: Install the undercloud (oooq-extras)
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: no
  become: false
  roles:
    - { role: undercloud-deploy, tags: undercloud-deploy, working_dir: /home/stack }

# TODO install undercloud/overcloud with containers
# (extra_args: -e environments/docker.yaml, containerized_undercloud: true)
# see https://review.openstack.org/#/c/419040/ for undercloud
# Example vars:
#  vars:
#    extra_args: >
#      --control-scale 3
#      -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml
#      #OR for containers
#      -e environments/docker.yaml
#      --ntp-server pool.ntp.org
