---
- hosts: virthost
  any_errors_fatal: true
  gather_facts: true
  roles:
    # Fails to restart libvirt in the chrooted container
    #- environment/setup
    - libvirt/teardown
    - libvirt/setup/user
    - libvirt/setup/overcloud
    - libvirt/setup/undercloud

- hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  roles:
    - { role: tripleo-inventory }

- name: Install the undercloud
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: no
  roles:
    - { role: tripleo/undercloud }

#- name: Post undercloud install steps
#  hosts: undercloud
#  any_errors_fatal: true
#  gather_facts: no
#  roles:
#    - { role: tripleo-undercloud-post }

#- name: Deploy the overcloud
#  hosts: undercloud
#  gather_facts: no
#  roles:
#    - tripleo-overcloud

# OR install undercloud and HA overcloud
#- hosts: undercloud
#  vars:
#    extra_args: >
#      --control-scale 3
#      -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml
#      #OR for containers
#      -e environments/docker.yaml
#      --ntp-server pool.ntp.org
#  roles:
#    - overcloud

# TODO install undercloud/overcloud with containers
# (extra_args: -e environments/docker.yaml, containerized_undercloud: true)
# see https://review.openstack.org/#/c/419040/ for undercloud
