---
# Libvirt local deployments by quickstart
- name: Install delorian repos (oooq-extras)
  hosts: undercloud
  vars:
    repos:
      - type: tripleo-repos
        bundle: current
        release: master
  roles:
    - repo-setup

- name: Install the undercloud (oooq-extras)
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: true
  become: false
  vars_files:
    - vars/undercloud-local.yaml
  roles:
    - undercloud-deploy
