---
- name: Provision tasks
  hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  become: true
  roles:
    # https://review.openstack.org/#/c/447000/
    - { role: environment/setup, when: teardown|bool }
    - { role: libvirt/teardown, when: teardown|bool }
    - { role: libvirt/setup/user, when: teardown|bool, become: false }
    #- libvirt/setup/overcloud
    - libvirt/setup/undercloud

- name: Generate new inventory
  hosts: localhost
  any_errors_fatal: true
  # update ansible_user_dir from root, for ssh setup
  gather_facts: true
  become: false
  roles:
    - { role: tripleo-inventory, tags: undercloud-inventory }
