---
# Non local deployments by quickstart, hacking/racy mode for manual
# ansible-playbook calls interleaved by tags:

- name:  Deploy the overcloud (multinode)
  any_errors_fatal: true
  hosts: undercloud
  gather_facts: false
  become: false
  vars_files:
    - ../vars/overcloud-traas.yaml
  roles:
    - overcloud-deploy
  #TODO parametrize env vars for the deployed-server remaining roles
  #NOTE FooCustomRoleName_hosts must be explicitely exported
  environment:
    ControllerDeployedServer_hosts: "{{ lookup('env', 'CONTROLLER_HOSTS') }}"
    SUBNODES_SSH_KEY: "{{subnodes_ssh_key}}"
    OVERCLOUD_SSH_KEY: "{{subnodes_ssh_key}}"
    OVERCLOUD_SSH_USER: "{{ssh_user}}"
