---
# Libvirt local deployments by quickstart w/o overclouds expected
# and custom repodata. Do not use with quickstart's config/releases!
- name: Provision tasks
  hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  become: true
  vars_files:
    - ../vars/virthost-local.yaml
    - ../vars/repodata.yaml
  roles:
    - { role: environment/setup, when: teardown|bool }
    - { role: libvirt/teardown, when: teardown|bool }
    - role: libvirt/setup/user
      become: false
      ansible_user_id: "{{ non_root_user }}"
      when: teardown|bool
    - role: libvirt/setup/undercloud
      environment:
        SUPERMIN_KERNEL_VERSION: "{{ lookup('env', 'SUPERMIN_KERNEL_VERSION') }}"
        SUPERMIN_KERNEL: "{{ lookup('env', 'SUPERMIN_KERNEL') }}"
        SUPERMIN_MODULES:  "{{ lookup('env', 'SUPERMIN_MODULES') }}"
        LIBGUESTFS_BACKEND: "{{ lookup('env', 'LIBGUESTFS_BACKEND') }}"

- name: Generate new inventory
  hosts: localhost
  any_errors_fatal: true
  # update ansible_user_dir from root, for ssh setup
  gather_facts: true
  become: false
  vars_files:
    - ../vars/virthost-local.yaml
  roles:
    - tripleo-inventory
