---
# Libvirt local deployments by quickstart (no overclouds expected)
# may be used to deploy openshift-on-openstack
- name: Install delorian repos (oooq-extras)
  any_errors_fatal: true
  gather_facts: true
  become: true
  hosts: undercloud
  vars_files:
    - ../vars/repodata.yaml
  pre_tasks:
    - meta: clear_facts
  roles:
    - role: repo-setup
      local_working_dir: "{{ lookup('env', 'LWD') }}"
      working_dir: /home/{{ undercloud_user }}
      when: configure_repos|bool

- name: Install the client
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  become: true
  tasks:
    - package:
        name: python-tripleoclient*

- name: UC host prep tasks
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  vars:
    local_working_dir: "{{ lookup('env', 'LWD') }}"
    working_dir: /home/{{ undercloud_user }}
    undercloud_user: stack
  tasks:
    - name: Upload custom tht env files
      copy:
        src: /tmp/scripts/tht
        dest: "{{working_dir}}"
        force: yes
        owner: "{{undercloud_user}}"
      tags: upload
    - name: Allow docker CLI for user stack
      command: /usr/sbin/usermod -aG root,docker stack
      become: true

- name: Install the undercloud (oooq-extras)
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  # --use-heat installer can't be sudo'ed
  become: false
  roles:
    - role: undercloud-deploy
      local_working_dir: "{{ lookup('env', 'LWD') }}"
      working_dir: /home/{{ undercloud_user }}
