---
# Libvirt local deployments by quickstart (no overclouds expected)
# may be used to deploy openshift-on-openstack
- name: Install delorian repos (oooq-extras)
  any_errors_fatal: true
  gather_facts: true
  become: true
  hosts: undercloud
  vars_files:
    - ../vars/repodata.yaml
  pre_tasks:
    - meta: clear_facts
  roles:
    - role: repo-setup
      local_working_dir: "{{ lookup('env', 'LWD') }}"
      working_dir: /home/{{ undercloud_user }}
      when: configure_repos|bool

- name: Install the client
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  become: true
  tasks:
    - package:
        name: python-tripleoclient*

- name: UC host prep tasks
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  vars:
    local_working_dir: "{{ lookup('env', 'LWD') }}"
    working_dir: /home/{{ undercloud_user }}
    undercloud_user: stack
  vars_files:
    - ../tht/config/general_config/featureset127.yml
  tasks:
    - name: Upload custom tht env files
      copy:
        src: /tmp/scripts/tht
        dest: "{{working_dir}}"
        force: yes
        owner: "{{undercloud_user}}"
      tags: upload
    - name: Allow docker CLI for user stack
      command: /usr/sbin/usermod -aG root,docker stack
      become: true
    #FIXME: should be wired into undercloud.conf instead
    - name: hack in custom all-in-one role data
      command: >-
        cp -f
        /home/stack/tht/roles/UndercloudAIOOpenshift.yaml
        /usr/share/openstack-tripleo-heat-templates/roles_data_undercloud.yaml
      become: true
    # FIXME use custom undercloud_ip different to the one
    # generated with libivrt setup inventory tasks
    - name: use provisioned undercloud_ip hostvar as external IP
      set_fact:
        undercloud_external_ip: "{{ undercloud_ip }}"
        cacheable: true
    - name: override undercloud_ip hostvar as we want its internal IP
      set_fact:
        undercloud_ip: "{{ undercloud_local_ip }}"
        cacheable: true

- name: Install the undercloud (oooq-extras)
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  # --use-heat installer can't be sudo'ed
  become: false
  roles:
    - role: undercloud-deploy
      local_working_dir: "{{ lookup('env', 'LWD') }}"
      working_dir: /home/{{ undercloud_user }}
