---
# Non local deployments by quickstart
- name: Install delorian repos
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: true
  become: true
  vars_files:
    - ../vars/undercloud-traas.yaml
  roles:
    - {role: repo-setup,  when: configure_repos|bool}

- name: Install the client
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  become: true
  tasks:
    - package:
        name: python-tripleoclient

- name: Upload custom tht and prepare networking configs
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  vars_files:
    - ../vars/undercloud-traas.yaml
  become: true
  roles:
    - overcloud-prep-config

- name: Install the undercloud (oooq-extras)
  hosts: undercloud
  any_errors_fatal: true
  gather_facts: false
  become: true
  vars_files:
    - ../vars/undercloud-traas.yaml
  roles:
    - undercloud-deploy
